version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      timezone: "Asia/Tokyo"
    open-pull-requests-limit: 10
    ignore:
      - dependency-name: "typescript"
        update-types:
          - "version-update:semver-major"
    groups:
      typescript-eslint:
        patterns:
          - "@typescript-eslint/*"

      dev-dependencies:
        dependency-type: "development"
        patterns:
          - "*"
        exclude-patterns:
          - "@typescript-eslint/*"

      production-minor-patch:
        dependency-type: "production"
        update-types:
          - "minor"
          - "patch"
        patterns:
          - "*"
